# Generated by Django 5.0.7 on 2024-12-20 21:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
