services:

  web:
    build: .
    container_name: frenzy_clothing
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/app
      - frenzy_static_volume:/app/staticfiles
      - frenzy_media_volume:/app/media

    expose:
      - "8000"

    env_file:
      - .env

    depends_on:
      - db
      - redis

    networks:
      - frenzy_clothing_network


  db:
    image: postgres:15
    container_name: frenzy_clothing_db

    env_file:
      - .env

    volumes:
      - frenzy_postgres_data:/var/lib/postgresql/data

    networks:
      - frenzy_clothing_network


  redis:
    image: redis:7-alpine
    container_name: frenzy_clothing_redis

    restart: unless-stopped

    networks:
      - frenzy_clothing_network


networks:

  frenzy_clothing_network:
    name: frenzy_clothing_network


volumes:

  frenzy_postgres_data:
    name: frenzy_postgres_data

  frenzy_static_volume:
    name: frenzy_static_volume

  frenzy_media_volume:
    name: frenzy_media_volume