# Generated by Django 5.0.7 on 2024-12-28 23:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_coin_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
