# Generated by Django 5.0.7 on 2024-12-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_coin_qr_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='deactivation_reason',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deactivation_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_by',
        ),
    ]
